# Generated by Django 4.2.16 on 2024-11-10 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processo",
            name="autor",
            field=models.CharField(default="Autor Desconhecido", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="processo",
            name="data_ajuizamento",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="processo",
            name="reu",
            field=models.CharField(default="Réu Desconhecido", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="processo",
            name="status",
            field=models.CharField(
                choices=[("Em Andamento", "Em Andamento"), ("Concluído", "Concluído")],
                default="Em Andamento",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="processo",
            name="valor_causa",
            field=models.DecimalField(decimal_places=2, default="0.0", max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="processo",
            name="vara",
            field=models.CharField(default="Vara Desconhecida", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="processo",
            name="numero_processo",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
